import {
  User,
  Dog,
  Cat,
  Baby,
  Ghost,
  Skull,
  Crown,
  Glasses,
  Rocket,
  Sword,
  Wand2,
  Briefcase,
  GraduationCap,
  Stethoscope,
  ChefHat,
  Palette,
  Music,
  Camera,
  Gamepad2,
  Sparkles,
  Bot,
  Zap,
  Coffee,
  Anchor,
  Shield,
  BookOpen,
  Cpu,
  Shrink,
  HelpCircle,
  Mountain,
  Building2,
  TreePine,
  Waves,
  Moon,
  Sun,
  Cloud,
  Snowflake,
  Flame,
  Pizza,
  Cake,
  IceCream,
  Monitor,
  Train,
  Building,
  Tv,
  Ticket,
  Trash2,
  Clock,
  Heart,
  Star,
  Trophy,
  Target,
  Key,
  Lock,
  Map,
  Compass,
  Hourglass,
  Gift,
  Gem,
  Coins,
  UserX,
  Sparkle,
  Sunrise,
  UtensilsCrossed,
  BriefcaseBusiness,
  Brain,
  EyeOff,
  Medal,
  ServerCrash,
  type LucideIcon,
} from "lucide-react";

export interface SlotItem {
  icon: LucideIcon;
  label: string;
}

export const protagonists: SlotItem[] = [
  { icon: User, label: "A Regular Person" },
  { icon: Dog, label: "A Talking Dog" },
  { icon: Cat, label: "A Mysterious Cat" },
  { icon: Baby, label: "A Genius Baby" },
  { icon: Ghost, label: "A Friendly Ghost" },
  { icon: Skull, label: "A Reformed Villain" },
  { icon: Crown, label: "A Dethroned Monarch" },
  { icon: Glasses, label: "A Nerdy Scientist" },
  { icon: Rocket, label: "An Astronaut" },
  { icon: Sword, label: "A Retired Knight" },
  { icon: Wand2, label: "A Clumsy Wizard" },
  { icon: Briefcase, label: "A Burnt-out CEO" },
  { icon: GraduationCap, label: "A Time-Traveling Student" },
  { icon: Stethoscope, label: "A Robot Doctor" },
  { icon: ChefHat, label: "A Celebrity Chef" },
  { icon: Palette, label: "A Starving Artist" },
  { icon: Music, label: "A One-Hit Wonder" },
  { icon: Camera, label: "A Paparazzi" },
  { icon: Gamepad2, label: "A Pro Gamer" },
  { icon: Sparkles, label: "A Shy Vampire" },
  { icon: Shield, label: "A Single-Parent Superhero" },
  { icon: Bot, label: "An Alien Tourist" },
  { icon: Coffee, label: "A Conspiracy Barista" },
  { icon: Anchor, label: "A Pirate Influencer" },
  { icon: Cpu, label: "A Sentient Toaster" },
  { icon: Target, label: "A Retired Hitman" },
  { icon: BookOpen, label: "A Competitive Librarian" },
  { icon: Music, label: "A Musical Robot" },
  { icon: Shrink, label: "A Tiny Giant" },
  { icon: HelpCircle, label: "A Lost AI Assistant" },
];

export const settings: SlotItem[] = [
  { icon: Mountain, label: "On a Haunted Mountain" },
  { icon: Building2, label: "In a Dystopian City" },
  { icon: TreePine, label: "In an Enchanted Forest" },
  { icon: Waves, label: "On a Sinking Cruise Ship" },
  { icon: Moon, label: "On the Moon" },
  { icon: Sun, label: "In a World Without Night" },
  { icon: Cloud, label: "In a Floating City" },
  { icon: Snowflake, label: "In the Arctic" },
  { icon: Flame, label: "Inside a Volcano" },
  { icon: Zap, label: "During an Apocalypse" },
  { icon: Pizza, label: "In a Giant Restaurant" },
  { icon: Coffee, label: "In a Hipster Café" },
  { icon: Cake, label: "In Candyland" },
  { icon: IceCream, label: "In a Melting World" },
  { icon: Monitor, label: "Inside a Video Game" },
  { icon: Rocket, label: "On a Space Elevator" },
  { icon: Clock, label: "In a Time Loop Town" },
  { icon: Heart, label: "At a Wedding Gone Wrong" },
  { icon: Waves, label: "In a Secret Underwater Lab" },
  { icon: Train, label: "On a Train That Never Stops" },
  { icon: Building, label: "Inside a Museum at Night" },
  { icon: Tv, label: "In a Reality TV Show" },
  { icon: Ticket, label: "In a Deserted Theme Park" },
  { icon: Trash2, label: "On a Floating Junkyard" },
];

export const goals: SlotItem[] = [
  { icon: Heart, label: "Must Find True Love" },
  { icon: Star, label: "Must Become Famous" },
  { icon: Trophy, label: "Must Win a Competition" },
  { icon: Target, label: "Must Save the World" },
  { icon: Key, label: "Must Unlock a Secret" },
  { icon: Lock, label: "Must Escape a Prison" },
  { icon: Map, label: "Must Find a Treasure" },
  { icon: Compass, label: "Must Find Their Way Home" },
  { icon: Clock, label: "Must Stop Time" },
  { icon: Hourglass, label: "Must Reverse Aging" },
  { icon: Gift, label: "Must Deliver a Package" },
  { icon: Gem, label: "Must Steal a Diamond" },
  { icon: Coins, label: "Must Pay Off a Debt" },
  { icon: UserX, label: "Must Clear Their Name" },
  { icon: Sparkle, label: "Must Break a Curse" },
  { icon: Sunrise, label: "Must Survive Until Sunrise" },
  { icon: UtensilsCrossed, label: "Must Learn to Cook" },
  { icon: BriefcaseBusiness, label: "Must Win Back Their Job" },
  { icon: Brain, label: "Must Outsmart a Rival" },
  { icon: EyeOff, label: "Must Keep a Secret" },
  { icon: Medal, label: "Must Become a Legend" },
  { icon: ServerCrash, label: "Must Stop an AI Uprising" },
];

export function getRandomItem<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}
